---
title: "cog_net"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install, but don't load
install.packages("tidygraph")

library(pacman)
p_load(tidyverse, ggraph, tidytext, readxl, igraph)

# import group membership
a <- read_csv("cognet_anon.csv")
```

This is a mess. Just run everything.

If you want to do it yourself, I recommend checking this tutorial instead: https://kateto.net/netscix2016.html

# Long format
```{r long}
# a <- groups %>%
#   # every name on a separate row
#   unnest_tokens(label, members, token = "words") %>%
#   # import anonymous names ()
#   full_join(names, by = "label") %>%
#   # cleanup
#   select(-id, -label) %>%
#   rename(label = alter_ego) %>%
#   # group by group and sort alphabetically
#   arrange(group, label)

a2 <- a %>% 
  group_by(group) %>%
  # remove groups with single agent
  filter(n()>=2) %>% 
  # make combinations (no repetition) of agent pairs
  do(data.frame(t(combn(.$label, 2)), stringsAsFactors=FALSE)) %>%
  # remove NA groups
  filter(!is.na(group))
  
```


# Prepare for tidygraph
## Nodes
```{r nodes}
nodes <- a %>%
  select(-group) %>%
  # keep unique names
  filter(!duplicated(label)) %>%
  filter(!is.na(label)) %>%
  # sort names alphabetically
  arrange(label) %>%
  # rownames (for joining dataframes)
  rownames_to_column("id")

  
```


## Clean Edges
```{r}
a3 <- a2 %>%
  ungroup() %>%
  # copy order generated by combn()
  mutate(base_pair = paste0(X1, ":", X2),
         # switch around some names in order to avoid {name1, name2} != {name2, name1}
         # if name2 is early in the alphabet AND name1 is late in the alphabet: swith order
         # else, do nothing
         ordered_pair = case_when(
           X2 %in% nodes$label[1:25] & X1 %in% nodes$label[26:48] 
           ~ paste0(X2, ":", X1),
           TRUE ~ base_pair)) %>%
  # get rid of old order
  select(-X1, -X2, -base_pair) %>%
  # new name order
  separate(ordered_pair, into = c("X1", "X2"))
```


### edges net_1 (everything)
```{r}

```


### edges net_2_* (only study groups in S1+S2 and S3+S4)
```{r}
# sum up connections between agent pairs
pw_2_early <- a3 %>%
  filter(str_detect(group, "Sg_1|Sg_2")) %>%
  select(-group) %>%
  group_by(X1, X2) %>%
  summarise(weight = n()) %>% 
  ungroup() %>%
  mutate(weight = ifelse(weight == 3, 2, weight))

# turn names in pairs_weight to numbers (for technical purposes)
ed_study_early <- pw_2_early %>% 
  left_join(nodes, by = c("X1" = "label")) %>% 
  rename(from = id) %>%
  left_join(nodes, by = c("X2" = "label")) %>% 
  rename(to = id) %>%
  select(from, to, weight)

# sum up connections between agent pairs
pw_2_late <- a3 %>%
  filter(str_detect(group, "Sg_3|Sg_4")) %>%
  select(-group) %>%
  group_by(X1, X2) %>%
  summarise(weight = n()) %>% 
  ungroup() %>%
  mutate(weight = ifelse(weight == 3, 2, weight))

# turn names in pairs_weight to numbers (for technical purposes)
ed_study_late <- pw_2_late %>% 
  left_join(nodes, by = c("X1" = "label")) %>% 
  rename(from = id) %>%
  left_join(nodes, by = c("X2" = "label")) %>% 
  rename(to = id) %>%
  select(from, to, weight)
```


### edges (study groups)
```{r}
# sum up connections between agent pairs
pw_3 <- a3 %>%
  filter(str_detect(group, "Sg_")) %>%
  select(-group) %>%
  group_by(X1, X2) %>%
  summarise(weight = n()) %>% 
  ungroup()

# turn names in pairs_weight to numbers (for technical purposes)
ed_no_study <- pw_3 %>% 
  left_join(nodes, by = c("X1" = "label")) %>% 
  rename(from = id) %>%
  left_join(nodes, by = c("X2" = "label")) %>% 
  rename(to = id) %>%
  select(from, to, weight)
```


# Turn into network objects
```{r}
##
net_1 <- tidygraph::tbl_graph(nodes = nodes, edges = ed_everything, directed = FALSE)

##
net_2_early <- tidygraph::tbl_graph(nodes = nodes, edges = ed_study_early, directed = FALSE)
net_2_late <- tidygraph::tbl_graph(nodes = nodes, edges = ed_study_late, directed = FALSE)

##
net_3 <- tidygraph::tbl_graph(nodes = nodes, edges = ed_no_study, directed = FALSE)
```
